# Generated by Django 4.0.4 on 2022-05-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_home_greetings_1_alter_home_greetings_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='greetings_2',
        ),
    ]
