# Generated by Django 4.0.4 on 2022-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_name_alter_profile_social_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
