# Generated by Django 4.0.4 on 2022-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projects_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
