# Generated by Django 4.0.4 on 2022-05-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_about_career_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='profile/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
